title: MEI in MuseScore
description: Documentation for the MEI support in MuseScore
theme: just-the-docs

url: https://lpugin.github.io/musescore-mei-doc

#aux_links:
#  Template Repository: https://github.com/lpugin/musescore-mei-doc
